spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: meet-app
  datasource:
    url: jdbc:h2:mem:meetapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 9090

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "meetapp-very-secret-key-change-in-prod-please-use-a-longer-secret-value-1234567890"
    access-token-validity-seconds: 3600
  photos:
    upload-dir: "uploads/photos"

